# main ブランチに最新コードが push された際に、
# 事前に用意した include.txt で指定している必要なファイル、ディレクトリ群のみを
# preproduction ブランチにコミットする

name: Prepare release packages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Validate composer.json and composer.lock
    #   run: composer validate --strict

    # - name: Cache Composer packages
    #   id: composer-cache
    #   uses: actions/cache@v3
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-php-

    # - name: Install dependencies
    #   run: composer install --prefer-dist --no-progress

    # 秘密鍵を設置
    - name: ssh key generate
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # ssh rsync実行
    # -a コピー元のディレクトリを再帰的にオーナー・グループ・パーミッション・タイムスタンプをそのままコピーします。
    # -h でファイルサイズの視認性をよくする。
    # -v 詳細を出力する。
    # -z 圧縮転送
    # --delete 転送元に無いファイルをサーバー側から削除
    # -e ssh指定
    - name: Deploy
      run: rsync -ahvz --delete -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./src/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/cyancobra4/www/stage/NxPC78_1/

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
